src/main/java/com/HowBaChu/howbachu/config/SecurityConfig.java, src/main/java/com/HowBaChu/howbachu/controller/AuthController.java, src/main/java/com/HowBaChu/howbachu/controller/MemberController.java, src/main/java/com/HowBaChu/howbachu/domain/constants/ResponseCode.java, src/main/java/com/HowBaChu/howbachu/domain/entity/Member.java, src/main/java/com/HowBaChu/howbachu/exception/GlobalExceptionHandler.java, src/main/java/com/HowBaChu/howbachu/exception/constants/ErrorCode.java, src/main/java/com/HowBaChu/howbachu/repository/MemberRepository.java, src/main/java/com/HowBaChu/howbachu/service/MemberService.java, src/main/java/com/HowBaChu/howbachu/service/impl/MemberServiceImpl.java
=> [Feature] 회원정보 수정, 회원 삭제, 중복 검사 기능 개발

build.gradle, src/test/java/com/HowBaChu/howbachu/core/S3MockConfig.java, src/test/java/com/HowBaChu/howbachu/core/S3MockTest.java
- findify/s3mock 라이브러리를 사용해서 s3 연결 테스트
- mock이지만 실제 버킷 이름으로 맞추고 통합테스트를 진행
- 테스트 내용은 인메모리 안에서 진행됨.
close #31
=> [Test] S3 Mock 테스트

build.gradle, src/main/java/com/HowBaChu/howbachu/config/SecurityConfig.java, src/main/java/com/HowBaChu/howbachu/controller/TopicController.java, src/main/java/com/HowBaChu/howbachu/controller/VoteController.java, src/main/java/com/HowBaChu/howbachu/domain/constants/Option.java, src/main/java/com/HowBaChu/howbachu/domain/constants/ResponseCode.java, src/main/java/com/HowBaChu/howbachu/domain/dto/vote/VoteRequestDto.java, src/main/java/com/HowBaChu/howbachu/domain/entity/Vote.java, src/main/java/com/HowBaChu/howbachu/domain/entity/embedded/VotingStatus.java, src/main/java/com/HowBaChu/howbachu/exception/constants/ErrorCode.java, src/main/java/com/HowBaChu/howbachu/repository/VoteRepository.java, src/main/java/com/HowBaChu/howbachu/repository/custom/TopicRepositoryCustom.java, src/main/java/com/HowBaChu/howbachu/repository/custom/VoteRepositoryCustom.java, src/main/java/com/HowBaChu/howbachu/repository/impl/TopicRepositoryCustomImpl.java, src/main/java/com/HowBaChu/howbachu/repository/impl/VoteRepositoryImpl.java, src/main/java/com/HowBaChu/howbachu/service/VoteService.java, src/main/java/com/HowBaChu/howbachu/service/impl/VoteServiceImpl.java, src/test/java/com/HowBaChu/howbachu/controller/TopicControllerTest.java, src/test/java/com/HowBaChu/howbachu/controller/VoteControllerTest.java
투표 API 구현. 및 중복투표 되도록까지 구현하였음.
=> [Feature] 투표 기능 구현 및 Topic 부분 수정

src/main/java/com/HowBaChu/howbachu/controller/OpinController.java, src/main/java/com/HowBaChu/howbachu/controller/VoteController.java, src/main/java/com/HowBaChu/howbachu/domain/constants/ResponseCode.java, src/main/java/com/HowBaChu/howbachu/domain/constants/Selection.java, src/main/java/com/HowBaChu/howbachu/domain/dto/opin/OpinRequestDto.java, src/main/java/com/HowBaChu/howbachu/domain/dto/opin/OpinResponseDto.java, src/main/java/com/HowBaChu/howbachu/domain/dto/vote/VoteRequestDto.java, src/main/java/com/HowBaChu/howbachu/domain/entity/Member.java, src/main/java/com/HowBaChu/howbachu/domain/entity/Opin.java, src/main/java/com/HowBaChu/howbachu/domain/entity/Topic.java, src/main/java/com/HowBaChu/howbachu/domain/entity/Vote.java, src/main/java/com/HowBaChu/howbachu/domain/entity/embedded/SubTitle.java, src/main/java/com/HowBaChu/howbachu/domain/entity/embedded/VotingStatus.java, src/main/java/com/HowBaChu/howbachu/exception/constants/ErrorCode.java, src/main/java/com/HowBaChu/howbachu/repository/OpinRepository.java, src/main/java/com/HowBaChu/howbachu/repository/custom/OpinRepositoryCustom.java, src/main/java/com/HowBaChu/howbachu/repository/custom/TopicRepositoryCustom.java, src/main/java/com/HowBaChu/howbachu/repository/custom/VoteRepositoryCustom.java, src/main/java/com/HowBaChu/howbachu/repository/impl/TopicRepositoryCustomImpl.java, src/main/java/com/HowBaChu/howbachu/repository/impl/VoteRepositoryImpl.java, src/main/java/com/HowBaChu/howbachu/service/OpinService.java, src/main/java/com/HowBaChu/howbachu/service/impl/OpinServiceImpl.java, src/main/java/com/HowBaChu/howbachu/service/impl/TopicServiceImpl.java, src/main/java/com/HowBaChu/howbachu/service/impl/VoteServiceImpl.java, src/test/java/com/HowBaChu/howbachu/controller/TopicControllerTest.java, src/test/java/com/HowBaChu/howbachu/controller/VoteControllerTest.java, src/test/java/com/HowBaChu/howbachu/repository/OpinRepositoryTest.java, src/test/java/com/HowBaChu/howbachu/repository/TopicRepositoryTest.java, src/test/java/com/HowBaChu/howbachu/service/TopicServiceTest.java
=> Opin Create & Vote part update

src/main/java/com/HowBaChu/howbachu/controller/MemberController.java, src/main/java/com/HowBaChu/howbachu/domain/constants/ResponseCode.java, src/main/java/com/HowBaChu/howbachu/service/MemberService.java, src/main/java/com/HowBaChu/howbachu/service/impl/MemberServiceImpl.java, src/test/java/com/HowBaChu/howbachu/controller/AuthControllerTest.java, src/test/java/com/HowBaChu/howbachu/controller/MemberControllerTest.java, src/test/java/com/HowBaChu/howbachu/controller/TopicControllerTest.java, src/test/java/com/HowBaChu/howbachu/controller/VoteControllerTest.java, src/test/java/com/HowBaChu/howbachu/core/S3MockTest.java, src/test/java/com/HowBaChu/howbachu/repository/MemberRepositoryTest.java, src/test/java/com/HowBaChu/howbachu/repository/OpinRepositoryTest.java, src/test/java/com/HowBaChu/howbachu/repository/TopicRepositoryTest.java, src/test/java/com/HowBaChu/howbachu/service/MemberServiceTest.java, src/test/java/com/HowBaChu/howbachu/service/TopicServiceTest.java
- 회원정보 수정 시 비밀번호 검증 API 개발
- 테스트 코드 실행 시 AWS 의존성이 EC2 MetaData를 탐색하던 딜레이를 없애기 위한 옵션 추가
close #42
=> [Feature] 비밀번호 검증 API 개발

build.gradle, src/main/java/com/HowBaChu/howbachu/controller/AuthController.java, src/main/java/com/HowBaChu/howbachu/controller/MemberController.java, src/main/java/com/HowBaChu/howbachu/domain/dto/member/MemberRequestDto.java, src/main/java/com/HowBaChu/howbachu/domain/entity/Member.java, src/main/java/com/HowBaChu/howbachu/exception/ErrorResponse.java, src/main/java/com/HowBaChu/howbachu/exception/GlobalExceptionHandler.java, src/main/java/com/HowBaChu/howbachu/service/MemberService.java, src/main/java/com/HowBaChu/howbachu/service/impl/MemberServiceImpl.java, src/main/java/com/HowBaChu/howbachu/validation/EnumValid.java, src/main/java/com/HowBaChu/howbachu/validation/EnumValidator.java, src/test/java/com/HowBaChu/howbachu/controller/AuthControllerTest.java, src/test/java/com/HowBaChu/howbachu/controller/MemberControllerTest.java, src/test/java/com/HowBaChu/howbachu/service/MemberServiceTest.java
=> [Feature] member validation

src/main/java/com/HowBaChu/howbachu/controller/MemberController.java, src/main/java/com/HowBaChu/howbachu/domain/dto/member/MemberRequestDto.java
- Static Inner Class로 변경하여 Validation 적용
=> [Fix] password-verification-dto 수정

src/main/java/com/HowBaChu/howbachu/controller/TopicController.java, src/main/java/com/HowBaChu/howbachu/domain/constants/ResponseCode.java, src/main/java/com/HowBaChu/howbachu/domain/dto/topic/TopicResponseDto.java, src/main/java/com/HowBaChu/howbachu/repository/custom/TopicRepositoryCustom.java, src/main/java/com/HowBaChu/howbachu/repository/impl/TopicRepositoryImpl.java, src/main/java/com/HowBaChu/howbachu/service/TopicService.java, src/main/java/com/HowBaChu/howbachu/service/impl/TopicServiceImpl.java, src/main/resources/application.yml
close #54 
- 명예의 전당은 투표 수를 기준으로 20개의 토픽을 가져옵니다.
=> [Featrue] 명예의 전당 기능 추가

src/main/java/com/HowBaChu/howbachu/config/CorsConfig.java
- CorsConfig가 WebMvcConfigurer를 구현하도록 설정
- localhost:3000에 대한 모든 매핑 및 모든 메서드를 허락
=> [Fix] Cors 설정 변경

src/main/java/com/HowBaChu/howbachu/controller/MemberController.java
=> [Fix] MemberController에서 추가하지 않은 @Valid 어노테이션 추가

.gitignore, build.gradle, src/main/java/com/HowBaChu/howbachu/config/CacheConfig.java, src/main/java/com/HowBaChu/howbachu/controller/OpinController.java, src/main/java/com/HowBaChu/howbachu/controller/SearchController.java, src/main/java/com/HowBaChu/howbachu/domain/constants/ResponseCode.java, src/main/java/com/HowBaChu/howbachu/domain/dto/opin/OpinResponseDto.java, src/main/java/com/HowBaChu/howbachu/domain/dto/opin/OpinThreadResponseDto.java, src/main/java/com/HowBaChu/howbachu/domain/dto/search/SearchResultResponseDto.java, src/main/java/com/HowBaChu/howbachu/domain/dto/topic/TopicResponseDto.java, src/main/java/com/HowBaChu/howbachu/domain/entity/embedded/VotingStatus.java, src/main/java/com/HowBaChu/howbachu/repository/OpinRepository.java, src/main/java/com/HowBaChu/howbachu/repository/custom/OpinRepositoryCustom.java, src/main/java/com/HowBaChu/howbachu/repository/custom/TopicRepositoryCustom.java, src/main/java/com/HowBaChu/howbachu/repository/impl/OpinRepositoryImpl.java, src/main/java/com/HowBaChu/howbachu/repository/impl/TopicRepositoryImpl.java, src/main/java/com/HowBaChu/howbachu/service/OpinService.java, src/main/java/com/HowBaChu/howbachu/service/SearchService.java, src/main/java/com/HowBaChu/howbachu/service/impl/OpinServiceImpl.java, src/main/java/com/HowBaChu/howbachu/service/impl/SearchServiceImpl.java, src/main/java/com/HowBaChu/howbachu/service/impl/TopicServiceImpl.java, src/main/resources/data.sql
추가로, redis 설정 파일 수정해야할 부분
spring:
cache:
type: redis
redis:
**_host: redis_**
port: 6379
time-to-live: 3600000
=> 종합 검색 기능과 Redis 캐싱 적용 및 Opin API 부분 기능 수정

src/main/java/com/HowBaChu/howbachu/exception/constants/ErrorCode.java, src/main/java/com/HowBaChu/howbachu/service/impl/MemberServiceImpl.java
b883138c071fc42187fcbe2329a73b0d67c3871e : 회원가입, 회원정보 수정 시 이메일과 닉네임의 중복을 체크하고 익셉션을 찾는 기능을 추가했습니다. 또한, 회원가입시에는 모든 멤버에 대한 중복을 체크하고 회원정보 수정 시에는 나를 제외한 모든 회원에 대해서 체크하게 됩니다.
279b3d5c0788c49b5f70535048f25d51d45c820d : 기본 트랜잭션은 읽기 전용으로 설정하고 쓰기 기능이 있는 경우에만 따로 오버라이딩했습니다.
=> [Feature] member duplicated exception

src/main/java/com/HowBaChu/howbachu/domain/entity/Opin.java
- [] Opin 객체 delete 쿼리가 아닌, isDeleted 필드를 추가하여 해당 필드를 true 로 update 쿼리가 나가도록 설정.
=> :sparkles: Opin - Soft Delete 추가.

src/main/java/com/HowBaChu/howbachu/config/SecurityConfig.java, src/main/java/com/HowBaChu/howbachu/controller/VoteController.java, src/main/java/com/HowBaChu/howbachu/jwt/JwtFilter.java, src/main/java/com/HowBaChu/howbachu/jwt/JwtProvider.java, src/main/java/com/HowBaChu/howbachu/service/VoteService.java, src/main/java/com/HowBaChu/howbachu/service/impl/MemberServiceImpl.java, src/main/java/com/HowBaChu/howbachu/service/impl/VoteServiceImpl.java, src/main/java/com/HowBaChu/howbachu/utils/CookieUtil.java
- 9a84692bd6cca8a7f0d6b2f07c101c5e00a9d41d : 기존에 JwtProvider에 있던 쿠키 저장 메서드를 CookieUtil에서 하나로 통합했습니다.
- a6fcce9a4d957d05672563623f2dedf36f56db7a : 투표를 성공적으로 마친 경우 투표 정보가 쿠키에 저장됩니다.
- c904615f4e224278bddc8fca7255080ca9674812 : 투표를 한 사용자가 로그아웃 후 재로그인을 하면 투표 정보가 다시 쿠키로 저장됩니다.
=> [Feature] Vote Cookie

src/main/java/com/HowBaChu/howbachu/config/CorsConfig.java, src/main/java/com/HowBaChu/howbachu/config/SecurityConfig.java
- 로컬의 cors 에러로 인해 연동 목적으로 전체 cors 설정으로 변경합니다.
=> [Fix] cors 설정 임시 변경

src/main/java/com/HowBaChu/howbachu/controller/AuthController.java, src/main/java/com/HowBaChu/howbachu/controller/LikesController.java, src/main/java/com/HowBaChu/howbachu/controller/MemberController.java, src/main/java/com/HowBaChu/howbachu/controller/OpinController.java, src/main/java/com/HowBaChu/howbachu/controller/ReportController.java, src/main/java/com/HowBaChu/howbachu/controller/SearchController.java, src/main/java/com/HowBaChu/howbachu/controller/TopicController.java, src/main/java/com/HowBaChu/howbachu/controller/VoteController.java, src/main/java/com/HowBaChu/howbachu/domain/constants/ResponseCode.java
- aef064061753da2736b46fcd8ef1aaf50e8e907d : API마다 길게 호출되는 반환구문을 정적 팩토리 메소드로 대체하여 코드의 가독성을 높였습니다.
=> [Refactor] Response Entity 펙토리 메소드

src/main/java/com/HowBaChu/howbachu/domain/entity/RefreshToken.java, src/main/java/com/HowBaChu/howbachu/exception/ExceptionHandleFilter.java, src/main/java/com/HowBaChu/howbachu/jwt/JwtFilter.java, src/main/java/com/HowBaChu/howbachu/service/impl/MemberServiceImpl.java, src/main/java/com/HowBaChu/howbachu/validation/Email/EmailValidator.java
✅ TASKS
- 리프레쉬 토큰을 검사하는 과정에서 같은 토큰임에도 불일치가 발생하는 버그를 수정했습니다.
- 회원가입 시 중복 닉네임이 익셉션을 발생시키지 않는 버그를 수정했습니다.
=> [FIX] 회원 관리 버그 수정

build.gradle, src/main/java/com/HowBaChu/howbachu/domain/base/BaseEntity.java, src/main/java/com/HowBaChu/howbachu/repository/custom/MemberRepositoryCustom.java, src/main/java/com/HowBaChu/howbachu/repository/impl/TopicRepositoryImpl.java, src/main/java/com/HowBaChu/howbachu/service/impl/TopicServiceImpl.java, src/main/java/com/HowBaChu/howbachu/service/impl/VoteServiceImpl.java
d5bdb17 :bookmark: 0.0.7 SNAPSHOT - TEMP
47d1bd9 :zap: Member 조회 성능 최적화를 위한 캐싱 로직 추가
d67b6dd :zap: Topic 조회 API 성능 향상.
b07e3ff :sparkles: 생성/변경 시점 필드 -> JSON 직렬화/역직렬화 어노테이션 추가
=> 성능 최적화 및 JSON 직렬화/역직렬화 기능 추가를 포함한 버전 업데이트

src/main/java/com/HowBaChu/howbachu/domain/entity/Member.java, src/main/java/com/HowBaChu/howbachu/utils/CookieUtil.java
쿠키의 Same Site 옵션을 수정하여 서로 다른 Origin의 서드파티 쿠키가 정상적으로 송수신되도록 설정했습니다.
=> [Fix] Third Party Cookie fix

src/main/java/com/HowBaChu/howbachu/domain/entity/Member.java, src/main/java/com/HowBaChu/howbachu/repository/custom/MemberRepositoryCustom.java
=> [Fix] 삭제된 회원 조회 버그 수정

src/main/java/com/HowBaChu/howbachu/domain/entity/Member.java, src/main/java/com/HowBaChu/howbachu/domain/entity/Report.java, src/main/java/com/HowBaChu/howbachu/repository/custom/MemberRepositoryCustom.java, src/main/java/com/HowBaChu/howbachu/service/impl/ReportServiceImpl.java
신고받은 내역에 신고한 내역이 나오는 버그를 수정했습니다.
=> [FIx] 신고받은 내역 수정

src/main/java/com/HowBaChu/howbachu/domain/entity/Member.java, src/main/java/com/HowBaChu/howbachu/service/impl/MemberServiceImpl.java, src/main/java/com/HowBaChu/howbachu/validation/Email/EmailValid.java, src/main/java/com/HowBaChu/howbachu/validation/Email/EmailValidator.java, src/main/java/com/HowBaChu/howbachu/validation/MBTI/MBTIValid.java, src/main/java/com/HowBaChu/howbachu/validation/MBTI/MBTIValidator.java, src/main/java/com/HowBaChu/howbachu/validation/Password/PasswordValid.java, src/main/java/com/HowBaChu/howbachu/validation/Password/PasswordValidator.java, src/main/java/com/HowBaChu/howbachu/validation/StatusMessage/StatusMessageValid.java, src/main/java/com/HowBaChu/howbachu/validation/StatusMessage/StatusMessageValidator.java, src/main/java/com/HowBaChu/howbachu/validation/Username/UsernameValid.java, src/main/java/com/HowBaChu/howbachu/validation/Username/UsernameValidator.java
회원정보를 수정할 때 변경되지 않은 컬럼도 같이 보내야 했던 기존의 DTO 구조에서 변경된 컬럼만 포함해도 API 처리가 가능하도록 수정했습니다.
=> [Refactor] 회원정보 수정 시 필수 컬럼 제거

src/main/java/com/HowBaChu/howbachu/controller/MemberController.java, src/main/java/com/HowBaChu/howbachu/controller/OpinController.java, src/main/java/com/HowBaChu/howbachu/controller/SearchController.java, src/main/java/com/HowBaChu/howbachu/controller/VoteController.java, src/main/java/com/HowBaChu/howbachu/domain/constants/ResponseCode.java, src/main/java/com/HowBaChu/howbachu/domain/dto/opin/OpinResponseDto.java, src/main/java/com/HowBaChu/howbachu/domain/dto/opin/TrendingOpinResponseDto.java, src/main/java/com/HowBaChu/howbachu/domain/dto/search/SearchResultResponseDto.java, src/main/java/com/HowBaChu/howbachu/domain/entity/embedded/VotingStatus.java, src/main/java/com/HowBaChu/howbachu/exception/constants/ErrorCode.java, src/main/java/com/HowBaChu/howbachu/repository/custom/OpinRepositoryCustom.java, src/main/java/com/HowBaChu/howbachu/repository/custom/VoteRepositoryCustom.java, src/main/java/com/HowBaChu/howbachu/repository/impl/OpinRepositoryImpl.java, src/main/java/com/HowBaChu/howbachu/repository/impl/TopicRepositoryImpl.java, src/main/java/com/HowBaChu/howbachu/repository/impl/VoteRepositoryImpl.java, src/main/java/com/HowBaChu/howbachu/service/OpinService.java, src/main/java/com/HowBaChu/howbachu/service/SearchService.java, src/main/java/com/HowBaChu/howbachu/service/VoteService.java, src/main/java/com/HowBaChu/howbachu/service/impl/MemberServiceImpl.java, src/main/java/com/HowBaChu/howbachu/service/impl/OpinServiceImpl.java, src/main/java/com/HowBaChu/howbachu/service/impl/SearchServiceImpl.java, src/main/java/com/HowBaChu/howbachu/service/impl/VoteServiceImpl.java, src/test/java/com/HowBaChu/howbachu/controller/VoteControllerTest.java, src/test/java/com/HowBaChu/howbachu/repository/OpinRepositoryTest.java
코드의 부분 수정과 검증 로직 업데이트, 메소드 리팩토링 등의 유지보수 작업이 이루어졌습니다. 핫오핀용 DTO 생성, 페이징 및 핫오핀 기능, 핫오핀 캐싱 기능, 그리고 핫오핀 조회 기능 등의 새로운 기능이 추가되었습니다. 또한, 이메일 기반 검색 및 페이징 처리 업데이트, 로그인 쿠키 설정 개선, 토픽 검색 메소드 업데이트 등도 진행되었습니다. 추가로, fetchVoteStatus 메소드 추가와 OPIN_HOT_NOT_FOUND, OPIN_HOT 상태 코드 추가 등의 작업도 수행되었습니다
46961ed :white_check_mark: 테스트용 코드 부분 수정.
a447c64 :sparkles: 핫오핀용 DTO 생성
3f239f4 :recycle: 메소드 파라미터 및 이름 변경
501f288 :recycle: 이메일 기반 검색 및 페이징 처리 업데이트
a447c64 :sparkles: 핫오핀용 DTO 생성
3f239f4 :recycle: 메소드 파라미터 및 이름 변경
501f288 :recycle: 이메일 기반 검색 및 페이징 처리 업데이트
417b95b :sparkles: 페이징 및 핫오핀 기능 추가
19e60c6 :recycle: 투표 검증 로직 업데이트 및 메소드 리팩토링
f913537 :recycle: 이메일 기반 검색 및 페이징 기능 추가
5a5127c :sparkles: 핫오핀 캐싱 기능 추가 및 메소드 업데이트
69894f0 :recycle: 리팩토링 및 로그인 쿠키 설정 개선
bedd482 :recycle: 토픽 검색 메소드 업데이트 및 세부 정보 표현 개선
b435c6f :sparkles: …
=> 핫오핀 기능 추가 및 페이징, 검색 기능 강화를 위한 코드 리팩토링
